# Generated by Django 6.0 on 2026-07-29 07:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facility', '0485_rename_patientmobileotp_mobileotp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FillySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('history', models.JSONField(default=dict)),
                ('meta', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('created', 'Created'), ('recording', 'Recording'), ('processing', 'Processing'), ('completed', 'Completed'), ('partial', 'Partial'), ('failed', 'Failed'), ('expired', 'Expired')], db_index=True, default='created', max_length=16)),
                ('templates', models.JSONField(blank=True, default=list)),
                ('language_hint', models.JSONField(blank=True, default=list)),
                ('patient_details', models.JSONField(blank=True, null=True)),
                ('additional_data', models.JSONField(blank=True, default=dict)),
                ('chunk_indexes', models.JSONField(blank=True, default=list)),
                ('audio_files', models.JSONField(blank=True, default=list)),
                ('transcript', models.TextField(blank=True, null=True)),
                ('template_results', models.JSONField(blank=True, default=dict)),
                ('processing_errors', models.JSONField(blank=True, default=list)),
                ('usage', models.JSONField(blank=True, null=True)),
                ('finalize_task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('finalize_attempts', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('internal_name', models.CharField(blank=True, max_length=255, null=True)),
                ('audio_mime_type', models.CharField(blank=True, max_length=64, null=True)),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filly_sessions', to='facility.facility')),
                ('updated_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filly_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Filly Session',
                'verbose_name_plural': 'Filly Sessions',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='FillyUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('history', models.JSONField(default=dict)),
                ('meta', models.JSONField(default=dict)),
                ('input_tokens', models.IntegerField(default=0)),
                ('output_tokens', models.IntegerField(default=0)),
                ('audio_seconds', models.IntegerField(default=0, help_text='Estimated recorded audio duration')),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filly_usages', to='facility.facility')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usages', to='care_filly.fillysession')),
                ('updated_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filly_usages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Filly Usage',
                'verbose_name_plural': 'Filly Usages',
            },
        ),
        migrations.CreateModel(
            name='FillyUserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('history', models.JSONField(default=dict)),
                ('meta', models.JSONField(default=dict)),
                ('filly_enabled', models.BooleanField(default=False)),
                ('tnc_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('tnc_accepted_date', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='filly_preference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Filly User Preference',
                'verbose_name_plural': 'Filly User Preferences',
            },
        ),
        migrations.CreateModel(
            name='FillyQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('history', models.JSONField(default=dict)),
                ('meta', models.JSONField(default=dict)),
                ('tokens', models.IntegerField(default=0, help_text='Monthly token pool (facility row) or allowance (user row)')),
                ('tokens_per_user', models.IntegerField(default=0, help_text='Allowance copied to each user quota (facility rows only)')),
                ('allow_filly', models.BooleanField(default=True, help_text='Whether filly is enabled for this user/facility')),
                ('tnc_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('tnc_accepted_date', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filly_quotas', to='facility.facility')),
                ('updated_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, help_text='Null for the facility-level quota row', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filly_quotas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Filly Quota',
                'verbose_name_plural': 'Filly Quotas',
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted', False), ('user__isnull', True)), fields=('facility',), name='care_filly_unique_facility_quota'), models.UniqueConstraint(condition=models.Q(('deleted', False)), fields=('user', 'facility'), name='care_filly_unique_user_facility_quota')],
            },
        ),
    ]
