# Generated by Django 6.0 on 2026-08-16 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care_filly', '0002_medispeaksession'),
    ]

    operations = [
        migrations.AddField(
            model_name='medispeaksession',
            name='usage_recorded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
