# Generated by Django 6.0 on 2026-08-16 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care_filly', '0003_medispeaksession_usage_recorded_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='fillysession',
            name='medispeak_session_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.DeleteModel(
            name='MedispeakSession',
        ),
    ]
